site_name: howtos
repo_name: vilmarap/howtos
repo_url: https://github.com/vilmarap/howtos

theme:
  name: material
  language: pt
  palette: 
    - scheme: default
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode
    - scheme: slate 
      toggle: 
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github-alt
  logo: img/logo.png
  favicon: img/favicon.ico
  features:
  - content.tabs.link

markdown_extensions:
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.superfences
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - md_in_html

nav:
  - Home: index.md
  - Docs: docs.md
  - Banco de Dados: index.md
    - mysql: banco-de-dados/mysql.md
#    - postgres: banco-de-dados/postgres.md
#    - SQL Server: banco-de-dados/sqlserver.md
  - Controle de versão: index.md
#    - Git: controle-de-versao/git.md
#    - Github: controle-de-versao/github.md
#    - DatabaseVersioning: controle-de-versao/databaseversioning.md
  - E-mail: index.md
#    - Gmail: e-mail/gmail.md
  - Ferramentas: ferramentas/teste-infra.md
  - Gerência de Configuração: index.md
#    - Ansible no windows: gerencia-de-configuracao/ansible-windows.md
  - Monitoramento: index.md
#    - New Relic: monitoramento/newrelic.md
  - Nuvem: index.md
#    - AWS: nuvem/iam.md
#    - Azure: nuvem/appregistration.md
  - Orquestração: index.md
#    - AWS ECS: orquestracao/ecs.md
#    - Kubernetes: orquestracao/kubernetes.md
#    - Docker Swarm: orquestracao/dockerswarm.md
#    - Rancher: orquestracao/rancher.md
  - Provisionamento: index.md
#    - Terraform Azure: provisionamento/terraform-azure.md
#    - Terraform AWS: provisionamento/terraform-aws.md
  - Redes: index.md
#    - Firewall Fortigate: redes/fwfortigate.md
#    - Nginx: redes/nginx.md
  - Segurança: seguranca/index.md
  - Sistema operacional: sistema-operacional/index.md
#    - Ubuntu: sistema-operacional/ubuntu.md
#    - Windows: windows/index.md
#      - windows-server: sistema-operacional/windows-server.md
#      - windows-10: sistema-operacional/windows10.md
#    - CentOS: sistema-operacional/centos.md
  
