site_name: howtos
repo_name: vilmarap/howtos
repo_url: https://github.com/vilmarap/howtos

theme:
  name: material
  language: pt
  palette: 
    - scheme: default
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode
    - scheme: slate 
      toggle: 
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github-alt
  logo: img/logo.png
  favicon: img/favicon.ico
  features:
  - content.tabs.link

markdown_extensions:
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.superfences
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - md_in_html

nav:
  - Home: index.md
  - Docs: docs.md
  - Banco de Dados:
    - mysql: banco-de-dados/mysql.md
    - postgres: banco-de-dados/postgres.md
    - SQL Server: banco-de-dados/sqlserver.md
  - Controle de versão: 
    - Git: controle-de-versao/git.md
    - Github: controle-de-versao/github.md
    - DatabaseVersioning: controle-de-versao/databaseversioning.md
  - E-mail:
    - Gmail: e-mail/gmail.md
  - Ferramentas: ferramentas/teste-infra.md
  - Gerência de Configuração: 
    - Ansible: gerencia-de-configuracao/ansible-windows.md
  - Monitoramento: 
    - New Relic: monitoramento/newrelic.md
  - Nuvem:
    - AWS: nuvem/aws/iam.md
    - Azure: nuvem/azure/appregistration.md
  - Orquestração: 
    - AWS ECS: orquestracao/ecs.md
    - Kubernetes: orquestracao/kubernetes.md
    - Docker Swarm: orquestracao/dockerswarm.md
    - Rancher: orquestracao/rancher.md
  - Provisionamento: 
    - Terraform Azure: provisionamento/terraform-azure.md
    - Terraform AWS: provisionamento/terraform-aws.md
  - Redes: 
    - Firewall Fortigate: 
    - Nginx: redes/nginx.md
  - Segurança: seguranca/index.md
  - Sistema operacional: 
    - Ubuntu: sistema-operacional/ubuntu.md
    - Windows:
      - windows-server: sistema-operacional/windows-server.md
      - windows-10: sistema-operacional/windows10.md
    - CentOS: sistema-operacional/centos.md
